export const openApiSpec = {
  openapi: "3.0.3",
  info: {
    title: "Jobizy API",
    version: "2.0.0",
    description:
      "API REST Jobizy alignee sur le modele V1 centre sur la mise en relation, les offres, les messages, les missions, les avis, les litiges et les abonnements prestataires.",
  },
  servers: [
    { url: "http://localhost:3001/api/v1", description: "Local" },
    { url: "https://api.jobizy.com/api/v1", description: "Production" },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
      },
    },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    "/auth/register": { post: { tags: ["Auth"], summary: "Creer un compte utilisateur", security: [] } },
    "/auth/login": { post: { tags: ["Auth"], summary: "Authentifier un utilisateur", security: [] } },
    "/auth/google": { post: { tags: ["Auth"], summary: "Authentifier un utilisateur avec Google", security: [] } },
    "/auth/refresh": { post: { tags: ["Auth"], summary: "Rafraichir le token" } },
    "/auth/logout": { post: { tags: ["Auth"], summary: "Terminer la session" } },
    "/users/me": {
      get: { tags: ["Users"], summary: "Retourner l'utilisateur courant" },
      patch: { tags: ["Users"], summary: "Mettre a jour le profil utilisateur courant" },
    },
    "/jobizy/platform-settings": { get: { tags: ["Configuration"], summary: "Lire la configuration publique", security: [] } },
    "/categories": { get: { tags: ["Catalogue"], summary: "Lister les categories actives", security: [] } },
    "/services": { get: { tags: ["Catalogue"], summary: "Lister les services actifs", security: [] } },
    "/zones": { get: { tags: ["Zones"], summary: "Lister les zones", security: [] } },
    "/providers/activate": { post: { tags: ["Providers"], summary: "Activer le role prestataire" } },
    "/provider-profiles/me": {
      get: { tags: ["Providers"], summary: "Lire mon profil prestataire" },
      patch: { tags: ["Providers"], summary: "Modifier mon profil prestataire" },
    },
    "/requests": {
      post: { tags: ["Requests"], summary: "Creer une demande" },
      get: { tags: ["Requests"], summary: "Lister mes demandes" },
    },
    "/requests/{id}": {
      get: { tags: ["Requests"], summary: "Lire une demande" },
      patch: { tags: ["Requests"], summary: "Modifier une demande" },
    },
    "/requests/{id}/publication-preview": { post: { tags: ["Requests"], summary: "Retourner un recapitulatif indicatif sans paiement interne" } },
    "/requests/{id}/publish": { post: { tags: ["Requests"], summary: "Publier une demande" } },
    "/requests/{id}/close": { post: { tags: ["Requests"], summary: "Clore une demande" } },
    "/requests/{id}/award": { post: { tags: ["Requests"], summary: "Choisir une offre et creer la mission" } },
    "/matches": { get: { tags: ["Matching"], summary: "Lister les demandes visibles pour le prestataire" } },
    "/quotes": {
      get: { tags: ["Quotes"], summary: "Lister les offres" },
      post: { tags: ["Quotes"], summary: "Envoyer une offre prestataire" },
    },
    "/quotes/{id}": { patch: { tags: ["Quotes"], summary: "Modifier une offre" } },
    "/quotes/{id}/withdraw": { post: { tags: ["Quotes"], summary: "Retirer une offre" } },
    "/quotes/{id}/reject": { post: { tags: ["Quotes"], summary: "Refuser une offre cote client" } },
    "/missions": { get: { tags: ["Missions"], summary: "Lister mes missions" } },
    "/missions/{id}": { get: { tags: ["Missions"], summary: "Lire une mission" } },
    "/missions/{id}/complete": { post: { tags: ["Missions"], summary: "Terminer une mission" } },
    "/missions/{id}/cancel": { post: { tags: ["Missions"], summary: "Annuler une mission" } },
    "/conversations": { get: { tags: ["Messages"], summary: "Lister mes conversations" } },
    "/conversations/{id}/messages": {
      get: { tags: ["Messages"], summary: "Lister les messages d'une conversation" },
      post: { tags: ["Messages"], summary: "Envoyer un message" },
    },
    "/messages/{id}": { patch: { tags: ["Messages"], summary: "Marquer un message comme lu" } },
    "/notifications": { get: { tags: ["Notifications"], summary: "Lister mes notifications" } },
    "/notifications/read-all": { post: { tags: ["Notifications"], summary: "Marquer toutes mes notifications comme lues" } },
    "/notification-preferences": { get: { tags: ["Notifications"], summary: "Lire mes preferences de notification" } },
    "/notification-preferences/{id}": { patch: { tags: ["Notifications"], summary: "Mettre a jour mes preferences de notification" } },
    "/plans": { get: { tags: ["Subscriptions"], summary: "Lister les plans prestataires" } },
    "/subscriptions": { get: { tags: ["Subscriptions"], summary: "Lister mes abonnements" } },
    "/subscriptions/activate": { post: { tags: ["Subscriptions"], summary: "Activer ou changer un plan sans checkout integre" } },
    "/reviews": {
      get: { tags: ["Reviews"], summary: "Lister les avis" },
      post: { tags: ["Reviews"], summary: "Creer un avis" },
    },
    "/disputes": {
      get: { tags: ["Disputes"], summary: "Lister les litiges" },
      post: { tags: ["Disputes"], summary: "Ouvrir un litige" },
    },
    "/disputes/{id}/messages": {
      get: { tags: ["Disputes"], summary: "Lister les messages d'un litige" },
      post: { tags: ["Disputes"], summary: "Envoyer un message de litige" },
    },
    "/admin/me/access": { get: { tags: ["Admin"], summary: "Lire les permissions admin courantes" } },
    "/admin/overview": { get: { tags: ["Admin"], summary: "Lire le tableau de bord admin simplifie" } },
    "/admin/platform-settings": {
      get: { tags: ["Admin"], summary: "Lire la configuration plateforme" },
      patch: { tags: ["Admin"], summary: "Mettre a jour la configuration plateforme" },
    },
    "/admin/requests": { get: { tags: ["Admin"], summary: "Lister les demandes cote admin" } },
    "/admin/requests/{id}": { patch: { tags: ["Admin"], summary: "Mettre a jour une demande cote admin" } },
    "/admin/quotes": { get: { tags: ["Admin"], summary: "Lister les offres cote admin" } },
    "/admin/quotes/{id}": { patch: { tags: ["Admin"], summary: "Mettre a jour une offre cote admin" } },
    "/admin/missions": { get: { tags: ["Admin"], summary: "Lister les missions cote admin" } },
    "/admin/missions/{id}": { patch: { tags: ["Admin"], summary: "Mettre a jour une mission cote admin" } },
    "/admin/subscriptions": { get: { tags: ["Admin"], summary: "Lister les abonnements cote admin" } },
    "/admin/subscriptions/{id}": { patch: { tags: ["Admin"], summary: "Mettre a jour un abonnement cote admin" } },
    "/admin/disputes": { get: { tags: ["Admin"], summary: "Lister les litiges cote admin" } },
    "/admin/disputes/{id}": { patch: { tags: ["Admin"], summary: "Mettre a jour un litige cote admin" } },
  },
} as const;
